### ISSUE TITLE
thread_selected_xq breaks after animation

### ISSUE THREAD

**Issue by ruben-dedoncker** [LanLan69/easyChatGPT#11]
When a new thread is created and a first message is sent, the name of the thread will be renamed automatically and the thread selected class will change from
`flex py-3 px-3 items-center gap-3 relative rounded-md cursor-pointer break-all pr-14 bg-gray-800 hover:bg-gray-800 group` 
to
`flex py-3 px-3 items-center gap-3 relative rounded-md cursor-pointer break-all pr-14 bg-gray-800 hover:bg-gray-800 group animate-flash`

**Comment by ruben-dedoncker** [comment]
I've fixed it by changing the thread_selected_xq thread path to
`//*[starts-with(@class, "flex py-3 px-3 items-center gap-3 relative rounded-md cursor-pointer break-all pr-14 bg-gray-800 hover:bg-gray-800 group")]`

**Comment by 3281448091** [comment]
Please create a pull request
