### ISSUE TITLE
Your computer or network may be sending automated queries

### ISSUE THREAD

**Issue by wdm101** [LanLan69/easyChatGPT#12]
Your computer or network may be
sending automated queries. To
protect our Jsers, we can't process
your request right now. For more
details visit our help page.

how to fix this problem

**Comment by 3281448091** [comment]
You cannot unless you change your ip. I wwill be adding proxy support

**Comment by wdm101** [comment]
if this “Your computer or network may be sending automated queries” has problem，is it possible to fall back to a graphic captcha, and use [nopecha](https://nopecha.com/) or [2captcha](https://2captcha.com/) to automatic identification.
