### ISSUE TITLE
Error logging in

### ISSUE THREAD

**Issue by ghoshanjega** [LanLan69/easyChatGPT#3]
Not sure if it's related to captcha. It goes too fast

`(base) ➜  knowledge git:(main) ✗ /opt/homebrew/bin/python3 /Users/ghoshmac/Documents/code/k
nowledge/miniproj/chatgpt/chat.py
Browser successfully launched, logging in to account...
Traceback (most recent call last):
  File "/Users/ghoshmac/Documents/code/knowledge/miniproj/chatgpt/chat.py", line 7, in <module>
    chat = ChatClient(OPENAI_EMAIL,OPENAI_PASSWORD)
  File "/opt/homebrew/lib/python3.10/site-packages/easychatgpt/chatgpt.py", line 44, in __init__
    self.__login(username, password)
  File "/opt/homebrew/lib/python3.10/site-packages/easychatgpt/chatgpt.py", line 68, in __login
    email_box.send_keys(username)
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 234, in send_keys
    Command.SEND_KEYS_TO_ELEMENT, {"text": "".join(keys_to_typing(value)), "value": keys_to_typing(value)}
  File "/opt/homebrew/lib/python3.10/site-packages/selenium/webdriver/common/utils.py", line 148, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()
(base) ➜  knowledge git:(main) ✗ `

**Comment by 3281448091** [comment]
Please elaborate

**Comment by rehanzo** [comment]
I'm getting the same thing, testing with the example code in the README. The browser opens, login is clicked. It goes to the login screen, and the cursor is in the email field, then throws this error. 

edit: seems for me, the environment variables for the credentials were not being set properly. Maybe adding some error checking for cases like this would be helpful. @ghoshanjega, check if your envars are being set properly.

**Comment by 3281448091** [comment]
@RAR27 You are corrrect, I experienced the same problem today. You have to configure the environment correctly, I used dotenv to access the .env variables correctly.

```python
from easychatgpt import ChatClient
import os
from dotenv import load_dotenv


load_dotenv()
OPENAI_EMAIL = os.getenv("OPENAI_EMAIL")
OPENAI_PASSWORD = os.getenv("OPENAI_PASSWORD")

chat = ChatClient(OPENAI_EMAIL,OPENAI_PASSWORD)

answer = chat.interact("Introduce your self")

print(answer)
```

Another solution is just to put your password and email in ChatClient so that it doesn't have to read the .env file. 

```python
from easychatgpt import ChatClient

chat = ChatClient("YOUR EMAIL","YOUR PASSWORD")

answer = chat.interact("Introduce your self")

print(answer)
```

**Comment by ghoshanjega** [comment]
Thank you. Seems like it was a local config issue
