### ISSUE TITLE
我运行了你提供的demo，出现以下报错

### ISSUE THREAD

**Issue by 1529960009** [LanLan69/easyChatGPT#4]
![image](https://user-images.githubusercontent.com/45947734/209422628-bc62456c-aee6-400b-8f9a-c35a1be9e9aa.png)

**Comment by 3281448091** [comment]
缺少package，你试一下pip install pocketsphinx 如果接下来还有这个报错的话你就继续pip install 需要的包
<img width="382" alt="截屏2022-12-24 10 43 34" src="https://user-images.githubusercontent.com/91493509/209442948-4b5c86bd-5956-4639-91aa-258299e0e864.png">
