### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by Chastex** [LanLan69/easyChatGPT#6]
Collecting easychatgpt
  Downloading https://files.pythonhosted.org/packages/d4/6e/be3239708e4d61a13e6e3bfb44876e2d226c0daac64c57405314edcf7134/easychatgpt-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xNRKSD/easychatgpt/setup.py", line 27, in <module>
        long_description=open("README.md", encoding="utf-8").read(),
    TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by acheong08** [comment]
encoding is built in. You might want to upgrade your Python version

**Comment by Chastex** [comment]
> 

which  version is available? python2.7 and python3.8 are not working

**Comment by Chastex** [comment]
3.8 version show a error:
```
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'long_description_content_type'
```

**Comment by acheong08** [comment]
I use 3.10 and it works

**Comment by 3281448091** [comment]
```
python -m pip install --upgrade pip
```
upgrade and see

**Comment by 3281448091** [comment]
Here is a StackOverflow solution https://stackoverflow.com/questions/12541370/typeerror-encoding-is-an-invalid-keyword-argument-for-this-function
